#修改TNAME: K2P 中的K2P为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同
name: Build R3G

on: 
  release:
    types: [published]
    
  #push:
  #  branches: 
  #    - master

  #schedule:
  #  - cron: 0 8 * * 5

  #watch:
  #  types: [started]

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget
    - name: Clone source code
      env:
        KERNEL: 3.4
      run: |
        if [ $KERNEL = "4.4" ] ; then
        git clone --depth=1 https://github.com/xusi-66/rt-n56u.git /opt/rt-n56u
        else
        git clone --depth=1 https://github.com/xusi-66/rt-n56u.git /opt/rt-n56u
        fi
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh
        mkdir -p /opt/images/
    - name: Build Firmware
      env:
        TNAME: MI-R3G
        KERNEL: 3.4
      run: |
        cd /opt/rt-n56u/trunk
        if [ ! -f configs/templates/$TNAME.config ] ; then
        echo "configs/templates/$TNAME.config not found "
        exit 1
        fi
        cp -f configs/templates/$TNAME.config .config
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' .config
        ################################################################################################
        #因不同型号配置功能不一样，所以先把配置项删除，如果你自己要添加其他的，也要写上删除这一条，切记！！！
        ################################################################################################
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MENTOHUST=/d' .config #MENTOHUST
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_SERVER/d' .config #删除配置项SOFTETHERVPN
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CLIENT/d' .config #删除配置项SOFTETHERVPN
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CMD/d' .config #删除配置项SOFTETHERVPN 
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=/d' .config #SCUTCLIENT 锐捷认证
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=/d' .config #SS plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SSSERVER=/d' .config #SS server
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER=/d' .config #DNSFORWARDER       
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ADBYBY=/d' .config #adbyby plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPC=/d' .config #内网穿透FRPC
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TUNSAFE=/d' .config #TUNSAFE
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ALIDDNS=/d' .config #阿里DDNS
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SMARTDNS=/d' .config #smartdns
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SMARTDNSBIN=/d' .config #smartdns二进制文件
        sed -i '/CONFIG_FIRMWARE_INCLUDE_V2RAY=/d' .config #集成v2ray执行文件（3.8M左右)，如果不集成，会从网上下载下来执行，不影响正常使用
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TROJAN=/d' .config #集成trojan执行文件(1.1M左右)，如果不集成，会从网上下载下来执行，不影响正常使用
        sed -i '/CONFIG_FIRMWARE_INCLUDE_KOOLPROXY=/d' .config #KP广告过滤
        sed -i '/CONFIG_FIRMWARE_INCLUDE_CADDY=/d' .config #在线文件管理服务
        sed -i '/CONFIG_FIRMWARE_INCLUDE_CADDYBIN=/d' .config #集成caddu执行文件，此文件有13M,请注意固件大小。如果不集成，会从网上下载下来执行，不影响正常使用      
        sed -i '/CONFIG_FIRMWARE_INCLUDE_KUMASOCKS=/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ADGUARDHOME=/d' .config #去广告
        sed -i '/CONFIG_FIRMWARE_INCLUDE_IPT2SOCKS=/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MICROSOCKS=/d' .config        
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SRELAY=/d' .config #可以不集成
        sed -i '/CONFIG_FIRMWARE_INCLUDE_WYY=/d' .config #网易云解锁
        sed -i '/CONFIG_FIRMWARE_INCLUDE_WYYBIN=/d' .config #网易云解锁GO版本执行文件（4M多）注意固件超大小,不集成会自动下载
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ZEROTIER=/d' .config #zerotier ~1.3M
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ALDRIVER=/d' .config  #阿里云盘  ~3m
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SSOBFS=/d' .config # simple-obfs混淆插件 
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' .config
        ######################################################################
        #以下选项是定义你需要的功能（y=集成,n=忽略），重新写入到.config文件
        ######################################################################
        if [ $KERNEL = "4.4" ] ; then
        echo "CONFIG_FIRMWARE_INCLUDE_MENTOHUST=n" >> .config #MENTOHUST
        echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_SERVER=n" >> .config #SOFTETHERVPN
        echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CLIENT=n" >> .config #SOFTETHERVPN
        echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CMD=n" >> .config #SOFTETHERVPN
        echo "CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=n" >> .config #SCUTCLIENT
        echo "CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=y" >> .config #SS plus+
        echo "CONFIG_FIRMWARE_INCLUDE_SSSERVER=n" >> .config #SS server
        echo "CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER=n" >> .config #DNSFORWARDER
        echo "CONFIG_FIRMWARE_INCLUDE_ADBYBY=y" >> .config #adbyby plus+
        echo "CONFIG_FIRMWARE_INCLUDE_FRPC=n" >> .config #内网穿透FRPC
        echo "CONFIG_FIRMWARE_INCLUDE_TUNSAFE=n" >> .config #TUNSAFE
        echo "CONFIG_FIRMWARE_INCLUDE_ALIDDNS=n" >> .config #阿里DDNS
        echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNS=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNSBIN=n" >> .config #smartdns二进制文件
        echo "CONFIG_FIRMWARE_INCLUDE_V2RAY=n" >> .config #v2ray二进制文件
        echo "CONFIG_FIRMWARE_INCLUDE_TROJAN=n" >> .config #集成trojan执行文件，如果不集成，会从网上下载下来执行，不影响正常使用
        echo "CONFIG_FIRMWARE_INCLUDE_KOOLPROXY=n" >> .config #KP广告过滤
        echo "CONFIG_FIRMWARE_INCLUDE_CADDY=n" >> .config #在线文件管理服务
        echo "CONFIG_FIRMWARE_INCLUDE_CADDYBIN=n" >> .config #集成caddu执行文件，此文件有13M,请注意固件大小。如果不集成，会从网上下载下来执行，不影响正常使用
        echo "CONFIG_FIRMWARE_INCLUDE_KUMASOCKS=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_ADGUARDHOME=n" >> .config #去广告
        echo "CONFIG_FIRMWARE_INCLUDE_IPT2SOCKS=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_MICROSOCKS=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_SRELAY=n" >> .config #可以不集成
        echo "CONFIG_FIRMWARE_INCLUDE_WYY=y" >> .config #网易云解锁
        echo "CONFIG_FIRMWARE_INCLUDE_WYYBIN=n" >> .config #网易云解锁GO版本执行文件（4M多）注意固件超大小
        echo "CONFIG_FIRMWARE_INCLUDE_ZEROTIER=y" >> .config #zerotier ~1.3M
        echo "CONFIG_FIRMWARE_INCLUDE_ALDRIVER=y" >> .config  #阿里云盘  ~3m
        echo "CONFIG_FIRMWARE_INCLUDE_SSOBFS=y" >> .config # simple-obfs混淆插件 
        fi
        #########################################################################################
        #自定义添加其它功能请参考源码configs/templates/目录下的config文件。按照上面的格式添加即可
        #格式如下：
        #sed -i '/自定义项/d' .config
        #echo "自定义项=y" >> .config
        #########################################################################################
        sudo ./clear_tree
        sudo ./build_firmware_modify $TNAME 0
        sudo mv -f images/*.trx /opt/images/
    - name : MI-R3G
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: MI-R3G
        path: /opt/images
